[project]
name = "backend"
version = "0.1.0"
description = "Project Z Backend API"
readme = "README.md"
authors = [
    { name = "joysahaice", email = "joysahaice0919@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn[standard]>=0.52.0",
]

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
